// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"Community_Basic","status":true,"description":"基本的なパラメーターを設定するプラグインです。","parameters":{"cacheLimit":"20","screenWidth":"816","screenHeight":"624","changeWindowWidthTo":"","changeWindowHeightTo":"","renderingMode":"auto","alwaysDash":"off"}},
{"name":"MadeWithMv","status":false,"description":"メイン画面へ進む前に、\"Made with MV\"のスプラッシュ画面もしくはカスタマイズされたスプラッシュ画面を表示します。","parameters":{"Show Made With MV":"true","Made with MV Image":"MadeWithMv","Show Custom Splash":"false","Custom Image":"","Fade Out Time":"120","Fade In Time":"120","Wait Time":"160"}},
{"name":"TMMapHpGauge","status":true,"description":"マップシーンに顔グラフィックとＨＰゲージを表示します。\r\n必要に応じてＭＰや変数などをゲージで表示することもできます。","parameters":{"gaugeWindowX":"0","gaugeWindowY":"0","gaugeWindowWidth":"310","gaugeWindowHeight":"128","gaugeA":"{\"type\":\"VN\",\"x\":\"12\",\"y\":\"12\",\"width\":\"288\",\"height\":\"36\",\"fontSize\":\"28\",\"param\":\"56\",\"max\":\"58\",\"name\":\"残り体力\",\"color\":\"#ff6070 #ffa040\"}","gaugeB":"{\"type\":\"VN\",\"x\":\"12\",\"y\":\"46\",\"width\":\"288\",\"height\":\"36\",\"fontSize\":\"28\",\"param\":\"57\",\"max\":\"59\",\"name\":\"天使の力\",\"color\":\"#3060ff #90B0ff\"}","gaugeC":"{\"type\":\"VN\",\"x\":\"12\",\"y\":\"80\",\"width\":\"288\",\"height\":\"36\",\"fontSize\":\"28\",\"param\":\"53\",\"max\":\"54\",\"name\":\"天使の力の蓄積量\",\"color\":\"#ff60c0 #ffa0e0\"}","gaugeD":"{\"type\":\"VN\",\"x\":\"12\",\"y\":\"80\",\"width\":\"288\",\"height\":\"36\",\"fontSize\":\"28\",\"param\":\"77\",\"max\":\"54\",\"name\":\"快楽の波\",\"color\":\"#ff60c0 #ffa0e0\"}","faceOffsetX":"-4","faceOffsetY":"-1000","stateIconMax":"4","stateIconX":"156","stateIconY":"24","goldWidth":"0","goldX":"12","goldY":"12","vnMax":"false","shakeTime":"4","startVisible":"false","windowOpacity":"0","collideOpacity":"0","messageBusyHide":"false","eventBusyHide":"false","useBattleScene":"false","gaugeWindowBattleX":"0","gaugeWindowBattleY":"0"}},
{"name":"OtherKeyInput","status":true,"description":"プラグイン内で指定したキーの入力を取得できるようにします","parameters":{}},
{"name":"DTextPicture","status":true,"description":"動的文字列ピクチャ生成プラグイン","parameters":{}},
{"name":"TYA_EnemyHPGauge","status":true,"description":"敵ターゲットウィンドウにＨＰゲージを表示させます。\r\n特定の敵のゲージを非表示にすることもできます。","parameters":{}},
{"name":"MKR_PlayerMoveForbid","status":true,"description":"(v1.0.5) プレイヤー移動禁止プラグイン","parameters":{"Default_Move_Flag":"22","Default_Menu_Flag":"false","Enter Flag":"false"}},
{"name":"FixImageLoading","status":true,"description":"画像ロード時のチラつき防止プラグイン","parameters":{}},
{"name":"TitleCommandPosition","status":true,"description":"タイトルコマンドウィンドウの位置を変更します。","parameters":{"Offset X":"60","Offset Y":"30","Width":"240","Background":"0"}}
];
